config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'actors#index'
  resources :actors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_attached_file :image, styles: { medium: "200x225>", thumb: "100x100>" }, default_url: ""
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      @actor = Actor.find(params[:id])
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:first_name, :last_name, :dob, :bio, :movies, :image_name, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true, html: { multipart: true }) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, id: :actor_first_name, :class => "form-control",  :placeholder=> "First name" %>
        </div>
        <div class="col">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, id: :actor_last_name, :class => "form-control",  :placeholder=> "Last name" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :date_of_birth %>
      <%= form.date_field :dob, id: :actor_dob, :class => "form-control",  :placeholder=> "Date of Birth" %>
    </div>
    <div class="form-group">
      <%= form.label :biography %>
      <%= form.text_area :bio, id: :actor_bio, :class => "form-control", :rows=> "3" %>
    </div>
    <div class="form-group">
      <%= form.label :additional_information %>
      <%= form.text_area :movies, id: :actor_movies, :class => "form-control", :rows=> "3" %>
    </div>
    <div class="form-group">
      <%= form.label :profession %>
      <%= form.text_field :image_name, id: :actor_image_name, :class => "form-control", :rows=> "3" %>
    </div>
    <div class="form-group">
      <%= form.submit :class => 'btn btn-primary btn-lg' %>
    </div>
  </form>
<% end %>

app/views/actors/edit.html.erb
<p id="notice"><%= notice %></p>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">EDIT</h1>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
            <div class="col-md-12">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text"><h2><%= @actor.first_name %>&nbsp;<%= @actor.last_name %></h2></p>
                  <p class="card-text">
                    <%= render 'form', actor: @actor %>
                  </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'Show', @actor, :class=>"btn btn-sm btn-outline-primary" %>
                      <%= link_to 'Back', actors_path, :class=>"btn btn-sm btn-outline-secondary" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </div>

    </div>
  </div>

</main>

app/views/actors/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<main role="main">

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <div class="card-group">
          <% @actors.each do |actor| %>
            <div class="col-md-3">
              <div class="card">
                <%= image_tag actor.image.url(:medium), :class => "card-img-top" %>
                <div class="card-body">
                  <h5 class="card-title"><%= actor.first_name %>&nbsp;<%= actor.last_name %></h5>
                  <p class="card-text"><h6>Date of Birth: <%= actor.dob.strftime('%m/%d/%Y') rescue "" %></h6></p>
                  <p class="card-text"><%= truncate(actor.movies, length:40) rescue "" %></p>
                </div>
                <div class="card-footer">
                  <div class="d-flex justify-content-center align-items-center">
                    <div class="btn-group">
                      <%= link_to 'View More', actor, :class=>"btn btn-sm btn-outline-danger btn-block" %>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          <% end %>
        </div>
      </div>

      <br />

      <div class="row" text-center>
          <div class="col-md-12">
            <section class="text-center">
                <div class="container">
                  <p>
                    <%= link_to 'Add New People', new_actor_path, :class =>"btn btn-outline-primary my-2" %>
                  </p>
                </div>
              </section>
          </div>
      </div>

    </div>
  </div>

</main>

app/views/actors/new.html.erb
<p id="notice"><%= notice %></p>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">ADD NEW ACTOR/ACTRESS</h1>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
            <div class="col-md-12">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">
                    <%= render 'form', actor: @actor %>
                  </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'Back', actors_path, :class=>"btn btn-sm btn-outline-secondary" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </div>

    </div>
  </div>

</main>

app/views/actors/show.html.erb
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading"><%= @actor.first_name %>&nbsp;<%= @actor.last_name %></h1>
    </div>
  </section>

    <div class="container">
      <div class="row">
            <div class="col-md-12">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text"><%= image_tag(@actor.image.url(:medium)) %></p>
                  <p class="card-text"><h1><%= @actor.first_name %>&nbsp;<%= @actor.last_name %></h1></p>
                  <p class="card-text"><strong>Date of Birth:</strong>&nbsp;&nbsp;<%= @actor.dob.strftime('%m/%d/%Y') rescue "" %></p>
                </div>

                <table class="table table-striped">
                  <tbody>
                    <tr>
                      <th scope="row">Biography</th>
                      <td>
                        <div class="text-left"><%= @actor.bio %></div>
                      </td>
                    </tr>
                    <tr>
                      <th scope="row">Additional Information</th>
                      <td>
                        <div class="text-left"><%= @actor.movies %></div>
                      </td>
                    </tr>
                    <tr>
                      <th scope="row">Profession</th>
                      <td>
                        <div class="text-left"><%= @actor.image_name %></div>
                      </td>
                    </tr>
                  </tbody>
                </table>

              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="btn-group">
                  <%= link_to 'Edit', edit_actor_path(@actor), :class=>"btn btn-sm btn-outline-primary btn-lg" %>
                  <%= link_to 'Back', actors_path(@actor), :class=>"btn btn-sm btn-outline-secondary btn-lg" %>
                </div>
              </div>
            </div>
      </div>

    </div>


</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 76px;
        }
      }

      /* Sticky footer styles
      -------------------------------------------------- */
      html {
        position: relative;
        min-height: 100%;
      }
      body {
        /* Margin bottom by footer height */
        margin-bottom: 60px;
      }
      .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 60px;
        line-height: 60px; /* Vertically center the text there */
        background-color: #f5f5f5;
      }


      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

      body > .container {
        padding: 20px 15px 0;
      }

      .footer > .container {
        padding-right: 15px;
        padding-left: 15px;
      }

      code {
        font-size: 80%;
      }
    </style>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <%= link_to "PEOPLE GALLERY", root_url, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <%= link_to "Home", root_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Add New People", new_actor_path, :class=>"nav-link" %>
            </li>
            <%- if current_user %>
              <li class="nav-link">Welcome <%= current_user.email %>!</li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?"}, :class=>"nav-link") %>
              </li>
            <% else %>
              <li>
                <%= link_to "Login", new_user_session_path, :class=>"nav-link" %>
              </li>
              <li>
                <%= link_to "Register", new_user_registration_path, :class=>"nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 text-center">
          <% flash.each do |a, b| %>
            <div class="alert alert-success"> <%= b %> </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>

    <footer class="footer">
      <div class="container">
        <span class="text-danger">Place sticky footer content here.</span>
      </div>
    </footer>

  </body>
</html>